# Manufacturers
post https://127.0.0.1:5000/manufacturers/new HTTP/1.1
content-type: application/json

[
    {
        "name": "AW Custom",
        "info": "While the world around us has moved to less demanding production techniques, AW Custom has stayed true to its original values based on craftsmanship and quality, that is why AW Custom products are able to last a lifetime. We are the keepers of a culture's ancient craft, a symbol of the airsoft gun maker's desire to stay true to tradition. Each stage of the process: from manufacturing to finishing, is a specialized skill that takes time and careful attention."
    },
    {
        "name": "6mmProShop",
        "info": "Established in 2011, 6mmProShop Inc. is a USA based manufacturer and distributor with a mission to bring law enforcement training, Airsoft sporting events, and military simulation to the next level. 6mmProShop features exclusive licensed products, unique innovations, and distribution rights of many exciting products from Japan, Europe, South America, and Asia. With headquarters located in the USA, 6mmProShop offers unmatched product support, inventory availability for resellers, and worldwide exclusive products!"
    },
    {
        "name": "SRC",
        "info": "SRC, which is short for Starrainbow Company, was founded in Taiwan back in 1993. It first started out as a wholesaling company focusing on supplying the domestic toy market. SRC distributed many popular brands from all over the world including scale models. SRC developed by that a very strong position in the market. Because of the ever growing interest in Airsoft throughout the globe, SRC decided to start selling imported Airsoft Guns. In the same time plans of starting in house manufacturing of Airsoft guns. The step from being a sales company to becoming a producing company is a major leap that involves huge investments. But the aim was clear, to become one of the world’s best Airsoft producers."
    },
    {
        "name": "ASG",
        "info": "ActionSportGames is a worldwide leader in the business of replica firearms and accessories manufacturing – including Airsoft guns, Airguns, CO2 guns and firearms replicas. We specialize in 1:1 scale replica guns and accessories for fun, action, sports, entertainment and collection. Today were proud to be recognized as the innovator and manufacturer of the CZ EVO3 A1 AEG and having introduced several Airsoft versions of this popular Airsoft gun to the market.One of our goals is to become the preferred supplier in the firearms replica business through worldwide license agreements, quality brands and premium service – before, during and after sales."
    },
    {
        "name": "Cybergun",
        "info": "Cybergun is the world leader in designing and distributing replica dummy weapons for video game aficionados, sport or outdoor shooting, and collectors."
    },
    {
        "name": "PTS",
        "info": "When it comes to training, simulation, and the ultimate experience, theres PTS and then theres everyone else. With RDT&E (Research, Development, Test & Evaluation) Teams in both USA and Asia and using the best materials and manufacturing processes, PTS Syndicate is committed to bringing the highest quality and most innovative products onto the market to meet and exceed the exacting standards of the most discriminating end user. PTS is also a prolific exclusive licensee of the latest and greatest products in the tactical market. We have an excellent reputation as a trusted license partner that works closely with our licensors to extend awareness of their brands into a new market space."
    },
    {
        "name": "Angel Custom",
        "info":  "Angel Custom was founded on a mission to promote satisfaction and excitement on the Airsoft battlefield. Founded by Airsofters searching for perfections, it is our joy and pride to present you our battle tested creations. We strive to provide quality products and services that are reliable and trustworthy to be worthy of the trust placed in us."
    },
    {
        "name": "Conder",
        "info": "Condor Outdoor founds its beginnings early on as a camping goods manufacturer. The earlier days of the company were more focused on getting people out into nature and experiencing the wonder of the outdoors. As our product line expanded, the demand for function focused gear instead of general storage became more prevalent and as the War on Terror started we could not keep up with the demand for our products.Our quality and price of the 3-day Assault Pack drew so much attention that it became the heart of our tactical product line. From here we've expanded from camping vests to tactical vests, and expanding the product offering to equip warfighters, law enforcement, and hunters with quality and affordable gear."
    },
    {
        "name": "CYMA",
        "info": "CYMA is among the oldest, most experienced and the largest Airsoft manufacturing facility in the world. Known for their unmatched quality control and professionalism, CYMA is selected to be the OEM of a vast amount of Airsoft products. Durability and performance meets affordability!"
    },
    {
        "name": "Evike Exclusive",
        "info": "Evike Exclusive provides superior outdoor recreational products. That is why we develop, innovate, and pioneer to bring you the perfect experience, service, and products."
    },
    {
        "name": "Matrix",
        "info": "Established in 2001 for Airsofters by Airsofters. Team Matrix thrive on the vision to better the sport of Airsoft with affordable high quality Airsoft equipment. With decades of experiences as Airsoft enthusiasts ourselves, we live, sleep, and breathe Airsoft. Matrix offers a wide selection of skirmish grade replicas from rifles to pistols, a wide variety of accessories, and tactical equipment from helmets to boots. It is the Matrix mission to prepare every Airsoft shooter the perfect experience!"
    },
    {
        "name": "EMG",
        "info": "The EMG vision is to manufacture products the world has never seen before; products we would put our name on, and products that hit the spot! EMG (Evike Manufacturing Group) was spawned from the realization that if you want something done exactly the way you want it, you need to do it yourself, and we did just that. We took our 16 years of knowledge as the market's lead retailer, our network of 300+ superior manufacturers, to work with inspiring top innovators in the firearms industry. That combined with the vision to invest into the Airsoft industry, an industry we believe in, EMG was born."
    },
    {
        "name": "Madbull",
        "info": "MAD BULL Airsoft, established in 2004, is world famous for it's Airsoft accessories. Our major focus points are: Airsoft guns, Airsoft Toy Launchers, Airsoft Toy B.B. Showers, and Upgrade kits.We have a very strong R&D team and we put a lot of effort in designing new and exciting new products for the airsoft community."
    },
    {
        "name": "ICS",
        "info": "ICS follows the market demand and has globalization and localization strategies. Local distributors, wholesalers, or dealers are our distribution channels to ensure our best products and best services can be delivered to the end users. We expect ourselves to be the market leader to explore and create the market.We take care of our brand and good will by constantly improving first tier R&D, middle tier production quality, and the last tier marketing capabilities. ICS keeps expanding the quality and quantity of R&D teams. Our product lines will be more and more completed by our excellent innovative and developing capabilities. All of these make ICS the best Taiwan made AEG brand in every aspect."
    }
]